# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_test.ui'
#
# Created: Tue Apr 27 01:01:57 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.targetLabel = QtGui.QLabel(self.centralwidget)
        self.targetLabel.setObjectName("targetLabel")
        self.verticalLayout.addWidget(self.targetLabel)
        self.table = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setAcceptDrops(False)
        self.table.setColumnCount(2)
        self.table.setObjectName("table")
        self.table.setColumnCount(2)
        self.table.setRowCount(0)
        self.verticalLayout.addWidget(self.table)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.updateTargetButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateTargetButton.sizePolicy().hasHeightForWidth())
        self.updateTargetButton.setSizePolicy(sizePolicy)
        self.updateTargetButton.setObjectName("updateTargetButton")
        self.horizontalLayout.addWidget(self.updateTargetButton)
        self.optimizePushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optimizePushButton.sizePolicy().hasHeightForWidth())
        self.optimizePushButton.setSizePolicy(sizePolicy)
        self.optimizePushButton.setObjectName("optimizePushButton")
        self.horizontalLayout.addWidget(self.optimizePushButton)
        self.maxPowerButton = QtGui.QPushButton(self.centralwidget)
        self.maxPowerButton.setObjectName("maxPowerButton")
        self.horizontalLayout.addWidget(self.maxPowerButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_9.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ledListLabel = QtGui.QLabel(self.centralwidget)
        self.ledListLabel.setObjectName("ledListLabel")
        self.verticalLayout_2.addWidget(self.ledListLabel)
        self.LEDtable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEDtable.sizePolicy().hasHeightForWidth())
        self.LEDtable.setSizePolicy(sizePolicy)
        self.LEDtable.setColumnCount(3)
        self.LEDtable.setObjectName("LEDtable")
        self.LEDtable.setColumnCount(3)
        self.LEDtable.setRowCount(0)
        self.verticalLayout_2.addWidget(self.LEDtable)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sendPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendPushButton.sizePolicy().hasHeightForWidth())
        self.sendPushButton.setSizePolicy(sizePolicy)
        self.sendPushButton.setObjectName("sendPushButton")
        self.horizontalLayout_4.addWidget(self.sendPushButton)
        self.onPushButton = QtGui.QPushButton(self.centralwidget)
        self.onPushButton.setObjectName("onPushButton")
        self.horizontalLayout_4.addWidget(self.onPushButton)
        self.offPushButton = QtGui.QPushButton(self.centralwidget)
        self.offPushButton.setObjectName("offPushButton")
        self.horizontalLayout_4.addWidget(self.offPushButton)
        self.testPushButton = QtGui.QPushButton(self.centralwidget)
        self.testPushButton.setObjectName("testPushButton")
        self.horizontalLayout_4.addWidget(self.testPushButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_9.addWidget(self.line_3)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.numGenLabel = QtGui.QLabel(self.centralwidget)
        self.numGenLabel.setObjectName("numGenLabel")
        self.horizontalLayout_3.addWidget(self.numGenLabel)
        self.numGenLineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numGenLineEdit.sizePolicy().hasHeightForWidth())
        self.numGenLineEdit.setSizePolicy(sizePolicy)
        self.numGenLineEdit.setObjectName("numGenLineEdit")
        self.horizontalLayout_3.addWidget(self.numGenLineEdit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.statusLabel = QtGui.QLabel(self.centralwidget)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_3.addWidget(self.statusLabel)
        self.dataLabel = QtGui.QLabel(self.centralwidget)
        self.dataLabel.setObjectName("dataLabel")
        self.verticalLayout_3.addWidget(self.dataLabel)
        self.dataTextBrowser = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTextBrowser.sizePolicy().hasHeightForWidth())
        self.dataTextBrowser.setSizePolicy(sizePolicy)
        self.dataTextBrowser.setObjectName("dataTextBrowser")
        self.verticalLayout_3.addWidget(self.dataTextBrowser)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_9.addWidget(self.line_4)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.singleLEDLabel = QtGui.QLabel(self.centralwidget)
        self.singleLEDLabel.setObjectName("singleLEDLabel")
        self.verticalLayout_4.addWidget(self.singleLEDLabel)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ledNumLabel = QtGui.QLabel(self.centralwidget)
        self.ledNumLabel.setObjectName("ledNumLabel")
        self.horizontalLayout_5.addWidget(self.ledNumLabel)
        self.ledNumSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.ledNumSpinBox.setMaximum(31)
        self.ledNumSpinBox.setObjectName("ledNumSpinBox")
        self.horizontalLayout_5.addWidget(self.ledNumSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.dutyCycleLabel = QtGui.QLabel(self.centralwidget)
        self.dutyCycleLabel.setObjectName("dutyCycleLabel")
        self.horizontalLayout_6.addWidget(self.dutyCycleLabel)
        self.dutyCycleSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.dutyCycleSpinBox.setMaximum(100)
        self.dutyCycleSpinBox.setObjectName("dutyCycleSpinBox")
        self.horizontalLayout_6.addWidget(self.dutyCycleSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.led2SpinBox = QtGui.QSpinBox(self.centralwidget)
        self.led2SpinBox.setMaximum(31)
        self.led2SpinBox.setObjectName("led2SpinBox")
        self.horizontalLayout_8.addWidget(self.led2SpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.dutyCycle2SpinBox = QtGui.QSpinBox(self.centralwidget)
        self.dutyCycle2SpinBox.setMaximum(100)
        self.dutyCycle2SpinBox.setObjectName("dutyCycle2SpinBox")
        self.horizontalLayout_7.addWidget(self.dutyCycle2SpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.singleLEDButton = QtGui.QPushButton(self.centralwidget)
        self.singleLEDButton.setObjectName("singleLEDButton")
        self.verticalLayout_4.addWidget(self.singleLEDButton)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plot_1 = MplWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_1.sizePolicy().hasHeightForWidth())
        self.plot_1.setSizePolicy(sizePolicy)
        self.plot_1.setObjectName("plot_1")
        self.horizontalLayout_2.addWidget(self.plot_1)
        self.plot_2 = MplWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_2.sizePolicy().hasHeightForWidth())
        self.plot_2.setSizePolicy(sizePolicy)
        self.plot_2.setObjectName("plot_2")
        self.horizontalLayout_2.addWidget(self.plot_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.targetLabel.setBuddy(self.table)
        self.ledListLabel.setBuddy(self.LEDtable)
        self.numGenLabel.setBuddy(self.numGenLineEdit)
        self.dataLabel.setBuddy(self.dataTextBrowser)
        self.ledNumLabel.setBuddy(self.ledNumSpinBox)
        self.dutyCycleLabel.setBuddy(self.dutyCycleSpinBox)
        self.label.setBuddy(self.led2SpinBox)
        self.label_2.setBuddy(self.dutyCycle2SpinBox)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.table, self.LEDtable)
        MainWindow.setTabOrder(self.LEDtable, self.optimizePushButton)
        MainWindow.setTabOrder(self.optimizePushButton, self.sendPushButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.targetLabel.setText(QtGui.QApplication.translate("MainWindow", "Target Spectral Profile Input Data Points:", None, QtGui.QApplication.UnicodeUTF8))
        self.updateTargetButton.setText(QtGui.QApplication.translate("MainWindow", "Update Target", None, QtGui.QApplication.UnicodeUTF8))
        self.optimizePushButton.setText(QtGui.QApplication.translate("MainWindow", "Optimize", None, QtGui.QApplication.UnicodeUTF8))
        self.maxPowerButton.setText(QtGui.QApplication.translate("MainWindow", "Max Power", None, QtGui.QApplication.UnicodeUTF8))
        self.ledListLabel.setText(QtGui.QApplication.translate("MainWindow", "LED Information After Optimization:", None, QtGui.QApplication.UnicodeUTF8))
        self.sendPushButton.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.onPushButton.setText(QtGui.QApplication.translate("MainWindow", "Turn On", None, QtGui.QApplication.UnicodeUTF8))
        self.offPushButton.setText(QtGui.QApplication.translate("MainWindow", "Turn Off", None, QtGui.QApplication.UnicodeUTF8))
        self.testPushButton.setText(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.numGenLabel.setText(QtGui.QApplication.translate("MainWindow", "Number of Algorithm Generations:", None, QtGui.QApplication.UnicodeUTF8))
        self.numGenLineEdit.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLabel.setText(QtGui.QApplication.translate("MainWindow", "Current status... data input", None, QtGui.QApplication.UnicodeUTF8))
        self.dataLabel.setText(QtGui.QApplication.translate("MainWindow", "Data Log:", None, QtGui.QApplication.UnicodeUTF8))
        self.singleLEDLabel.setText(QtGui.QApplication.translate("MainWindow", "LED Testing:", None, QtGui.QApplication.UnicodeUTF8))
        self.ledNumLabel.setText(QtGui.QApplication.translate("MainWindow", "LED 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.dutyCycleLabel.setText(QtGui.QApplication.translate("MainWindow", "Duty Cycle 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "LED 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Duty Cycle 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.singleLEDButton.setText(QtGui.QApplication.translate("MainWindow", "Turn on LEDs", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import MplWidget
